
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftMASMENOSleftPORDIVADD ALL ALTER AND AS ASC AUTO_INCREMENT AVG BEGIN BETWEEN BIGINT BOOLEAN BY CADENA CASE CHAR CHARACTER CHECK COLUMN COLUMNS CONCAT CONSTRAINT CREATE DATABASES DECIMAL DECIMAL DECLARE DEFAULT DELETE DESC DISTINCT DIV DOUBLE DROP ELSE END ENTERO ENUM ETIQUETA EXCEPT EXISTS FOREIGN FROM FULL FUNCTION GREATEST GROUP HAVING ID IF ILIKE IN INHERITS INNER INSERT INTEGER INTERSECT INTO JOIN KEY LEAST LEFT LIKE LIMIT MAS MAX MENOS MIN MODE MONEY NATURAL NOT NULL NUMERIC OFFSET ON OR ORDER OUTER OWNER POR PRIMARY PUNTOYCOMA REAL REFERENCES RENAME REPLACE RETURNS RIGHT SELECT SET SHOW SIMILAR SMALLINT SQRT SUBSTRING SUM TABLE TABLES TEXT THEN TO TYPE UNION UNIQUE UPDATE UPPER VALUES VARCHAR VARYING VIEW WHEN WHEREinicio               : operacionoperacion        : ENTERO MAS ENTERO\n                        | ENTERO MENOS ENTERO\n                        '
    
_lr_action_items = {'ENTERO':([0,4,5,],[3,6,7,]),'$end':([1,2,6,7,],[0,-1,-2,-3,]),'MAS':([3,],[4,]),'MENOS':([3,],[5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'inicio':([0,],[1,]),'operacion':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> inicio","S'",1,None,None,None),
  ('inicio -> operacion','inicio',1,'p_inicio','gramaticaAscendente.py',225),
  ('operacion -> ENTERO MAS ENTERO','operacion',3,'p_operacion','gramaticaAscendente.py',250),
  ('operacion -> ENTERO MENOS ENTERO','operacion',3,'p_operacion','gramaticaAscendente.py',251),
]
